# Generated by Django 5.0.6 on 2024-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='credential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
