# Generated by Django 5.0.6 on 2024-06-07 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_password_task_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='description',
        ),
        migrations.AlterField(
            model_name='credential',
            name='credential',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
