# Generated by Django 5.0.6 on 2024-06-10 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_credential_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
