# Generated by Django 5.0.6 on 2024-06-10 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_credential_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
