# Generated by Django 5.0.6 on 2024-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_credential_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='type',
            field=models.CharField(default='other', max_length=200),
            preserve_default=False,
        ),
    ]
